# Generated by Django 5.2.7 on 2025-12-09 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hike',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
